export const SWN = {
  scores: {
    str: "SWN.scores.str.long",
    dex: "SWN.scores.dex.long",
    con: "SWN.scores.con.long",
    int: "SWN.scores.int.long",
    wis: "SWN.scores.wis.long",
    cha: "SWN.scores.cha.long",
  },
  roll_type: {
    result: "=",
    above: "≥",
    below: "≤"
  },
  saves: {
    evasion: "SWN.saves.evasion",
    mental: "SWN.saves.mental",
    physical: "SWN.saves.physical",
    luck: "SWN.saves.luck",
  },
  skills: {
    admin: "SWN.skills.administer",
    connect: "SWN.skills.connect",
    convince: "SWN.skills.convince",
    craft: "SWN.skills.craft",
    exert: "SWN.skills.exert",
    heal: "SWN.skills.heal",
    know: "SWN.skills.know",
    lead: "SWN.skills.lead",
    magic: "SWN.skills.magic",
    notice: "SWN.skills.notice",
    perform: "SWN.skills.perform",
    pray: "SWN.skills.pray",
    punch: "SWN.skills.punch",
    ride: "SWN.skills.ride",
    sail: "SWN.skills.sail",
    shoot: "SWN.skills.shoot",
    sneak: "SWN.skills.sneak",
    stab: "SWN.skills.stab",
    survive: "SWN.skills.survive",
    trade: "SWN.skills.trade",
    work: "SWN.skills.work"
  },
  encumbLocation: {
    readied: "SWN.items.readied",
    stowed: "SWN.items.stowed",
    other: "SWN.items.other"
  },
  attackSkills: {
    punch: "SWN.skills.punch",
    shoot: "SWN.skills.shoot",
    stab: "SWN.skills.stab",
    magic: "SWN.skills.magic"
  },
  armor : {
    unarmored: "SWN.armor.unarmored",
    light: "SWN.armor.light",
    medium: "SWN.armor.medium",
    heavy: "SWN.armor.heavy",
    shield: "SWN.armor.shield",
  },
  colors: {
    green: "SWN.colors.green",
    red: "SWN.colors.red",
    yellow: "SWN.colors.yellow",
    purple: "SWN.colors.purple",
    blue: "SWN.colors.blue",
    orange: "SWN.colors.orange",
    white: "SWN.colors.white"
  },
  languages: [
    "Trade Cant",
    "Ancient Vothian",
    "Old Vothian",
    "Modern Vothian",
    "Ancient Olok",
    "Brass Speech",
    "Ancient Lin",
    "Emedian",
    "Ancient Osrin",
    "Thurian",
    "Ancient Khalan",
    "Llaigisan",
    "Anak Speech",
    "Predecessant",
    "Abased",
    "Recurrent",
    "Deep Speech"
  ],
  tags: {
    melee: "SWN.items.Melee",
    missile: "SWN.items.Missile",
    SR: "SWN.items.SR",
    TH: "SWN.items.2H",
    AP: "SWN.items.AP",
    FX: "SWN.items.FX",
    L: "SWN.items.L",
    R: "SWN.items.R",
    LL: "SWN.items.LL",
    N: "SWN.items.N",
    PM: "SWN.items.PM",
    S: "SWN.items.S",
    SS: "SWN.items.SS",
    T: "SWN.items.T",
  },
  tag_images: {
    melee: "/systems/swn/assets/melee.png",
    missile: "/systems/swn/assets/missile.png",
    SR: "/systems/swn/assets/slow_reload.png",
    TH: "/systems/swn/assets/twohanded.png",
    AP: "/systems/swn/assets/armor_piercing.png",
    FX: "/systems/swn/assets/fixed.png",
    L: "/systems/swn/assets/long.png",
    R: "/systems/swn/assets/reload.png",
    LL: "/systems/swn/assets/less_lethal.png",
    N: "/systems/swn/assets/numerous.png",
    PM: "/systems/swn/assets/precisely_murderous.png",
    S: "/systems/swn/assets/subtle.png",
    SS: "/systems/swn/assets/single_shot.png",
    T: "/systems/swn/assets/throwable.png",
  },
  tag_desc: {
    melee: "SWN.items.desc.Melee",
    missile: "SWN.items.desc.Missile",
    SR: "SWN.items.desc.SR",
    TH: "SWN.items.desc.2H",
    AP: "SWN.items.desc.AP",
    FX: "SWN.items.desc.FX",
    L: "SWN.items.desc.L",
    R: "SWN.items.desc.R",
    LL: "SWN.items.desc.LL",
    N: "SWN.items.desc.N",
    PM: "SWN.items.desc.PM",
    S: "SWN.items.desc.S",
    SS: "SWN.items.desc.SS",
    T: "SWN.items.desc.T"
  },
  monster_saves: {
    0: {
      label: "Normal Human",
      d: 14,
      w: 15,
      p: 16,
      b: 17,
      s: 18
    },
    1: {
      label: "1-3",
      d: 12,
      w: 13,
      p: 14,
      b: 15,
      s: 16
    },
    4: {
      label: "4-6",
      d: 10,
      w: 11,
      p: 12,
      b: 13,
      s: 14
    },
    7: {
      label: "7-9",
      d: 8,
      w: 9,
      p: 10,
      b: 10,
      s: 12
    },
    10: {
      label: "10-12",
      d: 6,
      w: 7,
      p: 8,
      b: 8,
      s: 10
    },
    13: {
      label: "13-15",
      d: 4,
      w: 5,
      p: 6,
      b: 5,
      s: 8
    },
    16: {
      label: "16-18",
      d: 2,
      w: 3,
      p: 4,
      b: 3,
      s: 6
    },
    19: {
      label: "19-21",
      d: 2,
      w: 2,
      p: 2,
      b: 2,
      s: 4
    },
    22: {
      label: "22+",
      d: 2,
      w: 2,
      p: 2,
      b: 2,
      s: 2
    },
  }
};